Request for code review
AymenBida/Members-only pull request #1
Opened 2021-02-16 14:54 UTC by AymenBida

### Members only

In this project we did : 

- Create users and posts models and controllers
- Use devise to authenticate users
- Create a feed page showing the posts and who made them if the user is logged in

2021-02-16 19:59 UTC, elmejdki requested changes
# status: require changes :recycle: 

Great job guys :clap: :100: :+1:, you were almost gonna meet all the requirements for this project, but you still have some minor changes :hammer: :wrench: :hammer_and_wrench:  to take care of.
Please take the comments below:
:point_down: :point_down: :point_down: :point_down: 

## Required Changes :red_circle: 

##### PostsController

* [ ] it uses `before_action` to restrict access to the `:new` and `:create` methods (uses ApplicationController helper method) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

##### Views & Helpers

* [ ] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)
* [ ] There should be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

### Please make all the required changes, before you submit another code review.
## Happy Coding :tophat: 
_If you have any questions or you need help don't hesitate to contact me on slack._
## _Zakariae El Mejdki_

2021-02-16 19:59 UTC, elmejdki commented on app/views/layouts/application.html.erb
> +            <% end %>
Please remove logic from here and put it in view helpers

2021-02-16 19:59 UTC, elmejdki commented on app/views/layouts/application.html.erb
> +          <% end %>
Please remove logic from here and put it in view helpers

2021-02-16 19:59 UTC, elmejdki commented on app/views/layouts/application.html.erb
> +      <% end %>
Please remove logic from here and put it in view helpers

2021-02-16 19:59 UTC, elmejdki commented on app/views/posts/index.html.erb
> +    <% end %>
Please remove logic from here and put it in view helpers

2021-02-17 10:18 UTC, mimipeshy commented
### STATUS :APPROVED :partying_face: 

Hey there @AymenBida and @AshakaE   :wave: :wave:  good job on working on the requested changes. This project is therefore approved. Go ahead and merge. All the best in the next milestones :man_technologist: 

Regards
Peris Ndanu

2021-02-17 10:26 UTC, closed without merging